#!/usr/bin/env ruby

require 'yaml'
require 'fileutils'

PLUGINS = YAML.load <<EOD
---
  digitaltoad:
    - vim-jade
  godlygeek:
    - tabular
  lukerandall:
    - haskellmode-vim
  msanders:
    - snipmate.vim
  tpope:
    - vim-abolish
    - vim-cucumber
    - vim-endwise
    - vim-fugitive
    - vim-git
    - vim-haml
    - vim-rails
    - vim-repeat
    - vim-sensible
    - vim-surround
    - vim-unimpaired
    - vim-vividchalk
  scrooloose:
    - nerdtree
    - nerdcommenter
EOD

def windows?
  RUBY_PLATFORM =~ /(win|w)32$/
end

def got_git?
  begin
    `git --version`
  rescue
    false
  end
end

def get_repo(author, repo)
  if File.exists? "#{DOTVIM}/bundle/#{repo}"
    puts "Pulling lates from #{repo}"
    FileUtils.cd "#{DOTVIM}/bundle/#{repo}"
    system "git pull origin master"
  else
    puts "Cloning repo #{repo}"
    FileUtils.cd "#{DOTVIM}/bundle/"
    system "git clone git://github.com/#{author}/#{repo}.git"
  end
end

def found_in_vimrc?(cmd)
  File.foreach(VIMRC) do |line|
    if line.include? cmd
      return true
    end
  end
  return false
end

def add_pathogen_cmd_to_top
  require 'tempfile'
  require 'fileutils'
  tmp = Tempfile.new('install_vim')
  begin
    tmp.puts PATHOGEN_CMD
    tmp.puts HELPTAGS_CMD
    tmp.puts
    IO.readlines(VIMRC).each do |item|
      tmp.print item
    end
    tmp.close
    FileUtils.copy_file(tmp.path, VIMRC)
  ensure
    tmp.close
    tmp.unlink
  end
end



DOTVIM = File.expand_path("~/#{windows? ? 'vimfiles' : '.vim'}")
VIMRC = File.expand_path("~/#{windows? ? '_vimrc' : '.vimrc'}")

puts "You need git." unless got_git?
autoload_dir = "#{DOTVIM}/autoload/"
bundle_dir = "#{DOTVIM}/bundle/"
FileUtils.mkdir_p(autoload_dir)
FileUtils.mkdir_p(bundle_dir)
FileUtils.cd bundle_dir
get_repo('tpope', 'vim-pathogen')
FileUtils.cp "#{bundle_dir}vim-pathogen/autoload/pathogen.vim", autoload_dir
PATHOGEN_CMD="call pathogen#infect()"
HELPTAGS_CMD="call pathogen#helptags()"

add_pathogen_cmd_to_top unless found_in_vimrc? PATHOGEN_CMD

PLUGINS.each do |author, plugins|
  plugins.each do |item|
    get_repo(author, item)
  end
end

